version: "3"

services:
  saleor-storefront:
    container_name: saleor-storefront
    image: docker.io/asifshiraz/saleor-storefront:latest
    restart: always
    ports:
      - 3030:3000
    environment:
      - HOSTNAME=0.0.0.0
      - SALEOR_API_URL=http://saleor-platform-api-1:8000/graphql/
    networks:
      - saleor_network
      - saleor-platform_saleor-backend-tier

  # Add more containers below (nginx, postgres, etc.)

networks:
  saleor_network:
    external: true
  saleor-platform_saleor-backend-tier:
    external: true
